- name : apache2 server deployment
  hosts: web
  become: true
  tasks:
    - name: update packages and install apache server
      apt:
        update-cache: yes
        name: apache2
        state: present  
    - name: start apache2 server
      service:
        name: apache2
        state: started
    - name: change apache2 port
      copy:
        src: ./ports.conf
        dest: /etc/apache2/ports.conf
        owner: root
        group: root
        mode: '0644'
    - name: change index file in server
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'    
    - name: restart service
      systemd:
        name: apache2
        state: restarted              