---
  - name: Start and enable sonar service
    systemd:
      name: sonar.service
      state: restarted
      enabled: true

  
  # - name: Start PostgreSQL service
  #   service: 
  #     name: postgresql 
  #     state: started 
  #     enabled: yes